### ISSUE TITLE
Option Menu

### ISSUE THREAD

**Issue by ZQUEMA** [MisterPeModder/Bomberman-Global-Offensive#9]
- [x] Master volume
- [x] Music volume
- [x] Languages
- [x] Profiles
- [x] Key Binding
- [x] Window mode (full screen, windowed, borderless windowed)
- [x] Window size
- [ ] Colorblind filter

**Comment by francoisbaudouin** [comment]
Video Option:

The user will be able to manage her window size. Some display range will be available (16:9 format only).
Possibility to set full-screen

**Comment by francoisbaudouin** [comment]
Audio Option:

The user can set the master volume of the game.
Sound & Music volume can be set separately.

**Comment by francoisbaudouin** [comment]
Key binds keyboard & Controller ; Commands : 

On top left under different option selection, get player profile who's select the option menu.

Three columns to manage users  commands :
 - Action
 - Key-binds keyboard 
 - Key-binds controller
 
We know we select a specific action when the key-binds have opaque effect.

**Comment by MisterPeModder** [comment]
Missing colorblind filter, reopening
